### ISSUE TITLE
Example Bartman 2021 fig 1 throws error in colab

### ISSUE THREAD

**Issue by josephhardinee** [atmos-cloud-sim-uj/PySDM#615]
The example notebook for bartman 2021 fig 1 when run in colab fails on the cell with
```python
simulation.run(ProgBarController())
```
with the error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-60f608a1bade> in <module>()
----> 1 simulation.run(ProgBarController())

5 frames
/usr/local/lib/python3.7/dist-packages/PyMPDATA/solver.py in advance(self, nt, mu_coeff, post_step, post_iter)
     52             raise NotImplementedError()
     53 
---> 54         post_iter = post_iter or PostIterNull()
     55 
     56         wall_time_per_timestep = self.stepper(nt, mu_coeff, post_step, post_iter,

TypeError: wrap() missing 1 required positional argument: 'cls'
```

**Comment by slayoo** [comment]
Thank you @josephhardinee!
I confirm I get the same on Colab.
Just checked locally and it worked. No problem on CI and this notebook is executed on every build. 
Seems the problem is with Colab using older Numba (0.51.2).
Stack overflow has a workaround described: https://stackoverflow.com/questions/35776154/how-to-use-python-class-with-numba
Stay tuned for a fix, thanks again!

**Comment by slayoo** [comment]
fix is on the way: https://github.com/atmos-cloud-sim-uj/PyMPDATA/pull/249

**Comment by slayoo** [comment]
Merged in PyMPDATA, bugfix release on PyPI: https://pypi.org/project/PyMPDATA/0.5/
Checked just now on Colab, all seems to work OK!
Thanks again for reporting
